mysecond/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

mysecond/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

mysecond/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone

class Article(models.Model):
    article_title = models.CharField("название статьи", max_length=200)
    article_text = models.TextField("текст статьи")
    pub_date = models.DateTimeField("дата публикации")

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField("имя автора", max_length=50)
    comment_text = models.CharField("текст комментария", max_length=200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

mysecond/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from .models import Article, Comment


def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404('*Статья не найдена*')

    latest_comments_list = a.comment_set.order_by('-id')[:10]
    return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})


def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404('*Статья не найдена*')

    a.comment_set.create(author_name =request.POST['name'], comment_text = request.POST['text'])

    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))

mysecond/templates/Base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}МЕГА БЛОГ{% endblock%}</title>
</head>
<body>
{% block content %}{% endblock%}
</body>
</html>

mysecond/templates/articles/detail.html
{% extends 'Base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

<h2>{{article.article_title}}</h2>

<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>

{% if article.was_published_recently %}
САМОЕ ГОРЯЧЕЕ))

{% endif %}

<hr>

{% if latest_comments_list %}

    {% for c in latest_comments_list %}
    <p>
        <strong>{{c.author_name}}</strong>
        <p>{{c.comment_text}}</p>
    </p>
    {% endfor %}

{% else %}
Комментариев пока нет)
{% endif%}

<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Имя, пожалуйста" name="name"><br>
    <textarea name="text" required="" placeholder="текст комментария" cols="30" rows="10"></textarea><br>

    <button type="submit">Оставить комментарий</button>

</form>

{% endblock %}

mysecond/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}

    {% if latest_articles_list %}

        {% for a in latest_articles_list %}
            <a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
        {% endfor %}

    {% else %}
        Статьи не найдены \(0^0)/
    {% endif %}

{% endblock %}